# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginStub(object):
    """Plugin service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/plugin.Plugin/GetInfo',
                request_serializer=plugin__pb2.InfoRequest.SerializeToString,
                response_deserializer=plugin__pb2.PluginInfo.FromString,
                _registered_method=True)
        self.Execute = channel.unary_stream(
                '/plugin.Plugin/Execute',
                request_serializer=plugin__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=plugin__pb2.ExecuteOutput.FromString,
                _registered_method=True)
        self.ReportExecutionSummary = channel.unary_unary(
                '/plugin.Plugin/ReportExecutionSummary',
                request_serializer=plugin__pb2.SummaryRequest.SerializeToString,
                response_deserializer=plugin__pb2.SummaryResponse.FromString,
                _registered_method=True)


class PluginServicer(object):
    """Plugin service definition
    """

    def GetInfo(self, request, context):
        """GetInfo returns plugin metadata and capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Execute runs the plugin with the given parameters and streams output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportExecutionSummary(self, request, context):
        """ReportExecutionSummary sends execution summary data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=plugin__pb2.InfoRequest.FromString,
                    response_serializer=plugin__pb2.PluginInfo.SerializeToString,
            ),
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=plugin__pb2.ExecuteRequest.FromString,
                    response_serializer=plugin__pb2.ExecuteOutput.SerializeToString,
            ),
            'ReportExecutionSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportExecutionSummary,
                    request_deserializer=plugin__pb2.SummaryRequest.FromString,
                    response_serializer=plugin__pb2.SummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plugin.Plugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plugin.Plugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Plugin(object):
    """Plugin service definition
    """

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plugin.Plugin/GetInfo',
            plugin__pb2.InfoRequest.SerializeToString,
            plugin__pb2.PluginInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/plugin.Plugin/Execute',
            plugin__pb2.ExecuteRequest.SerializeToString,
            plugin__pb2.ExecuteOutput.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportExecutionSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plugin.Plugin/ReportExecutionSummary',
            plugin__pb2.SummaryRequest.SerializeToString,
            plugin__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
