// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InfoRequest is empty for now but may contain fields in the future
type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{0}
}

// PluginInfo contains metadata about the plugin
type PluginInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ParameterSpecs map[string]*ParamSpec  `protobuf:"bytes,5,rep,name=parameter_specs,json=parameterSpecs,proto3" json:"parameter_specs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Auth           *Authorization         `protobuf:"bytes,6,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetParameterSpecs() map[string]*ParamSpec {
	if x != nil {
		return x.ParameterSpecs
	}
	return nil
}

func (x *PluginInfo) GetAuth() *Authorization {
	if x != nil {
		return x.Auth
	}
	return nil
}

// ParamSpec describes a plugin parameter
type ParamSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                                        // "string", "int", "float", etc.
	AllowedValues []string               `protobuf:"bytes,6,rep,name=allowed_values,json=allowedValues,proto3" json:"allowed_values,omitempty"` // if empty, any value is allowed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamSpec) Reset() {
	*x = ParamSpec{}
	mi := &file_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamSpec) ProtoMessage() {}

func (x *ParamSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamSpec.ProtoReflect.Descriptor instead.
func (*ParamSpec) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ParamSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParamSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParamSpec) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ParamSpec) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *ParamSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ParamSpec) GetAllowedValues() []string {
	if x != nil {
		return x.AllowedValues
	}
	return nil
}

// ExecuteRequest contains the parameters for plugin execution
type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        map[string]string      `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// ExecuteOutput represents a single output message from the execution
type ExecuteOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ExecuteOutput_Output
	//	*ExecuteOutput_Error
	//	*ExecuteOutput_Progress
	Content       isExecuteOutput_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteOutput) Reset() {
	*x = ExecuteOutput{}
	mi := &file_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOutput) ProtoMessage() {}

func (x *ExecuteOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOutput.ProtoReflect.Descriptor instead.
func (*ExecuteOutput) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteOutput) GetContent() isExecuteOutput_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ExecuteOutput) GetOutput() string {
	if x != nil {
		if x, ok := x.Content.(*ExecuteOutput_Output); ok {
			return x.Output
		}
	}
	return ""
}

func (x *ExecuteOutput) GetError() *Error {
	if x != nil {
		if x, ok := x.Content.(*ExecuteOutput_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ExecuteOutput) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Content.(*ExecuteOutput_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isExecuteOutput_Content interface {
	isExecuteOutput_Content()
}

type ExecuteOutput_Output struct {
	Output string `protobuf:"bytes,1,opt,name=output,proto3,oneof"` // Regular output message
}

type ExecuteOutput_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Error if execution fails
}

type ExecuteOutput_Progress struct {
	Progress *Progress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"` // Progress information
}

func (*ExecuteOutput_Output) isExecuteOutput_Content() {}

func (*ExecuteOutput_Error) isExecuteOutput_Content() {}

func (*ExecuteOutput_Progress) isExecuteOutput_Content() {}

// Error represents an execution error
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`       // Error code for programmatic handling
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"` // Additional error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// Progress represents execution progress
type Progress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PercentComplete float32                `protobuf:"fixed32,1,opt,name=percent_complete,json=percentComplete,proto3" json:"percent_complete,omitempty"`
	Stage           string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	CurrentStep     int32                  `protobuf:"varint,3,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	TotalSteps      int32                  `protobuf:"varint,4,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *Progress) GetPercentComplete() float32 {
	if x != nil {
		return x.PercentComplete
	}
	return 0
}

func (x *Progress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Progress) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *Progress) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

// SummaryRequest contains execution summary data
type SummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metrics       map[string]float64     `protobuf:"bytes,7,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryRequest) Reset() {
	*x = SummaryRequest{}
	mi := &file_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryRequest) ProtoMessage() {}

func (x *SummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryRequest.ProtoReflect.Descriptor instead.
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *SummaryRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *SummaryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SummaryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SummaryRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SummaryRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SummaryRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SummaryRequest) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// SummaryResponse contains the execution summary data
type SummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Duration      float64                `protobuf:"fixed64,4,opt,name=duration,proto3" json:"duration,omitempty"` // in milliseconds
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metrics       map[string]float64     `protobuf:"bytes,8,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummaryResponse) Reset() {
	*x = SummaryResponse{}
	mi := &file_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummaryResponse) ProtoMessage() {}

func (x *SummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummaryResponse.ProtoReflect.Descriptor instead.
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *SummaryResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *SummaryResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SummaryResponse) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SummaryResponse) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SummaryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SummaryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SummaryResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SummaryResponse) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Authorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source of authorization, e.g., "AD Group", "Repo", "Gitlab User"
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Allowed values for the source
	Values        []string `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorization) Reset() {
	*x = Authorization{}
	mi := &file_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorization) ProtoMessage() {}

func (x *Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorization.ProtoReflect.Descriptor instead.
func (*Authorization) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *Authorization) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Authorization) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_proto_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x12proto/plugin.proto\x12\x06plugin\"\r\n" +
	"\vInfoRequest\"\xae\x02\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12O\n" +
	"\x0fparameter_specs\x18\x05 \x03(\v2&.plugin.PluginInfo.ParameterSpecsEntryR\x0eparameterSpecs\x12)\n" +
	"\x04auth\x18\x06 \x01(\v2\x15.plugin.AuthorizationR\x04auth\x1aT\n" +
	"\x13ParameterSpecsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.plugin.ParamSpecR\x05value:\x028\x01\"\xbd\x01\n" +
	"\tParamSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12%\n" +
	"\x0eallowed_values\x18\x06 \x03(\tR\rallowedValues\"\x87\x01\n" +
	"\x0eExecuteRequest\x12:\n" +
	"\x06params\x18\x01 \x03(\v2\".plugin.ExecuteRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\rExecuteOutput\x12\x18\n" +
	"\x06output\x18\x01 \x01(\tH\x00R\x06output\x12%\n" +
	"\x05error\x18\x02 \x01(\v2\r.plugin.ErrorH\x00R\x05error\x12.\n" +
	"\bprogress\x18\x03 \x01(\v2\x10.plugin.ProgressH\x00R\bprogressB\t\n" +
	"\acontent\"O\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\x8f\x01\n" +
	"\bProgress\x12)\n" +
	"\x10percent_complete\x18\x01 \x01(\x02R\x0fpercentComplete\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12!\n" +
	"\fcurrent_step\x18\x03 \x01(\x05R\vcurrentStep\x12\x1f\n" +
	"\vtotal_steps\x18\x04 \x01(\x05R\n" +
	"totalSteps\"\x95\x03\n" +
	"\x0eSummaryRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12@\n" +
	"\bmetadata\x18\x06 \x03(\v2$.plugin.SummaryRequest.MetadataEntryR\bmetadata\x12=\n" +
	"\ametrics\x18\a \x03(\v2#.plugin.SummaryRequest.MetricsEntryR\ametrics\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xb4\x03\n" +
	"\x0fSummaryResponse\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x01R\bduration\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12A\n" +
	"\bmetadata\x18\a \x03(\v2%.plugin.SummaryResponse.MetadataEntryR\bmetadata\x12>\n" +
	"\ametrics\x18\b \x03(\v2$.plugin.SummaryResponse.MetricsEntryR\ametrics\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"?\n" +
	"\rAuthorization\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values2\xc9\x01\n" +
	"\x06Plugin\x124\n" +
	"\aGetInfo\x12\x13.plugin.InfoRequest\x1a\x12.plugin.PluginInfo\"\x00\x12<\n" +
	"\aExecute\x12\x16.plugin.ExecuteRequest\x1a\x15.plugin.ExecuteOutput\"\x000\x01\x12K\n" +
	"\x16ReportExecutionSummary\x12\x16.plugin.SummaryRequest\x1a\x17.plugin.SummaryResponse\"\x00B*Z(github.com/example/grpc-plugin-app/protob\x06proto3"

var (
	file_proto_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_proto_rawDescData []byte
)

func file_proto_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_proto_rawDescData
}

var file_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_plugin_proto_goTypes = []any{
	(*InfoRequest)(nil),     // 0: plugin.InfoRequest
	(*PluginInfo)(nil),      // 1: plugin.PluginInfo
	(*ParamSpec)(nil),       // 2: plugin.ParamSpec
	(*ExecuteRequest)(nil),  // 3: plugin.ExecuteRequest
	(*ExecuteOutput)(nil),   // 4: plugin.ExecuteOutput
	(*Error)(nil),           // 5: plugin.Error
	(*Progress)(nil),        // 6: plugin.Progress
	(*SummaryRequest)(nil),  // 7: plugin.SummaryRequest
	(*SummaryResponse)(nil), // 8: plugin.SummaryResponse
	(*Authorization)(nil),   // 9: plugin.Authorization
	nil,                     // 10: plugin.PluginInfo.ParameterSpecsEntry
	nil,                     // 11: plugin.ExecuteRequest.ParamsEntry
	nil,                     // 12: plugin.SummaryRequest.MetadataEntry
	nil,                     // 13: plugin.SummaryRequest.MetricsEntry
	nil,                     // 14: plugin.SummaryResponse.MetadataEntry
	nil,                     // 15: plugin.SummaryResponse.MetricsEntry
}
var file_proto_plugin_proto_depIdxs = []int32{
	10, // 0: plugin.PluginInfo.parameter_specs:type_name -> plugin.PluginInfo.ParameterSpecsEntry
	9,  // 1: plugin.PluginInfo.auth:type_name -> plugin.Authorization
	11, // 2: plugin.ExecuteRequest.params:type_name -> plugin.ExecuteRequest.ParamsEntry
	5,  // 3: plugin.ExecuteOutput.error:type_name -> plugin.Error
	6,  // 4: plugin.ExecuteOutput.progress:type_name -> plugin.Progress
	12, // 5: plugin.SummaryRequest.metadata:type_name -> plugin.SummaryRequest.MetadataEntry
	13, // 6: plugin.SummaryRequest.metrics:type_name -> plugin.SummaryRequest.MetricsEntry
	14, // 7: plugin.SummaryResponse.metadata:type_name -> plugin.SummaryResponse.MetadataEntry
	15, // 8: plugin.SummaryResponse.metrics:type_name -> plugin.SummaryResponse.MetricsEntry
	2,  // 9: plugin.PluginInfo.ParameterSpecsEntry.value:type_name -> plugin.ParamSpec
	0,  // 10: plugin.Plugin.GetInfo:input_type -> plugin.InfoRequest
	3,  // 11: plugin.Plugin.Execute:input_type -> plugin.ExecuteRequest
	7,  // 12: plugin.Plugin.ReportExecutionSummary:input_type -> plugin.SummaryRequest
	1,  // 13: plugin.Plugin.GetInfo:output_type -> plugin.PluginInfo
	4,  // 14: plugin.Plugin.Execute:output_type -> plugin.ExecuteOutput
	8,  // 15: plugin.Plugin.ReportExecutionSummary:output_type -> plugin.SummaryResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_plugin_proto_init() }
func file_proto_plugin_proto_init() {
	if File_proto_plugin_proto != nil {
		return
	}
	file_proto_plugin_proto_msgTypes[4].OneofWrappers = []any{
		(*ExecuteOutput_Output)(nil),
		(*ExecuteOutput_Error)(nil),
		(*ExecuteOutput_Progress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_proto = out.File
	file_proto_plugin_proto_goTypes = nil
	file_proto_plugin_proto_depIdxs = nil
}
